language: php
sudo: required
dist: xenial

matrix:
  include:
    - php: 7.3
      env: DB=mysqli # MyISAM
    - php: 7.4
      env: DB=mysqli
    - php: 7.4
      env: DB=mariadb
    - php: 7.4
      env: DB=postgres
    - php: 7.4
      env: DB=sqlite3
    - php: 7.2
      env: DB=mysqli
    - php: 7.1
      env: DB=mysqli
    - php: 8.0
      env: DB=mysqli
    - php: hhvm
      env: DB=mysqli
  allow_failures:
    - php: hhvm
  fast_finish: true

env:
  global:
    - EXTNAME="gn36/hookup"  # CHANGE name of the extension HERE
    - SNIFF="1"            # Should we run code sniffer on your code?
    - IMAGE_ICC="1"        # Should we run icc profile sniffer on your images?
    - EPV="1"              # Should we run EPV (Extension Pre Validator) on your code?
    - PHPBB_BRANCH="3.3.x"

branches:
  only:
    - master
    - develop
    - /^dev\/.*$/

install:
  - if [ "${TRAVIS_PHP_VERSION}" = "5.3.3" ]; then cat composer.json | sed 's/"version"/"config":{\n\t\t"disable-tls":true,\n\t\t"secure-http":false\n\t},\n\t"version"/' > composer.tmp.json ; mv composer.tmp.json composer.json ; fi
  - composer.phar self-update --1 # Enforce composer version 1 for now
  - composer.phar install --dev --no-interaction --prefer-source
  - chmod +x travis/prepare-phpbb.sh
  - travis/prepare-phpbb.sh $EXTNAME $PHPBB_BRANCH
  - travis/prepare-langtest.sh $EXTNAME $PHPBB_BRANCH
  - cd ../../phpBB3
  - travis/prepare-extension.sh $EXTNAME $PHPBB_BRANCH
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION

script:
  - sh -c "if [ '$SNIFF' != '0' ]; then travis/ext-sniff.sh $DB $TRAVIS_PHP_VERSION $EXTNAME; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION; fi"
  - phpBB/vendor/bin/phpunit --configuration phpBB/ext/$EXTNAME/travis/phpunit-$DB-travis.xml --bootstrap ./tests/bootstrap.php
  - sh -c "if [ '$EPV' != '0' ] && [ '$TRAVIS_PHP_VERSION' = '7.4' ] && [ '$DB' = 'mysqli' ]; then phpBB/ext/$EXTNAME/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/'; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.4' ] && [ '$DB' = 'mysqli' ]; then ../langtest/travis/test-lang.sh; fi"
